INSERT INTO INSUMO_PRIMARIO (ID, TIPO, CANTIDAD, UNIDAD, SUB_TIPO, CREATED_DATE, LAST_UPDATED_AT)
VALUES
    (1, 'PLASTICO', 0.0, 'KILOGRAMO', 'NEGRO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'PLASTICO', 0.0, 'KILOGRAMO', 'COLOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'TAPA', 0.0, 'UNIDAD', 'ROSCA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'TAPA', 0.0, 'UNIDAD', 'CALCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'ARO_GOMA', 0.0, 'UNIDAD', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 'ARO_GOMA', 0.0, 'UNIDAD', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 'ARO_GOMA', 0.0, 'UNIDAD', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'TORNILLOS', 0.0, 'UNIDAD', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 'TORNILLO_GRANDE', 0.0, 'UNIDAD', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 'TEE', 0.0, 'UNIDAD', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 'STICKER', 0.0, 'UNIDAD', 'TANQUE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12, 'STICKER', 0.0, 'UNIDAD', 'CAMARA_SEPTICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 'RAMAL', 0.0, 'UNIDAD', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 'RAMAL', 0.0, 'UNIDAD', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 'RAMAL', 0.0, 'UNIDAD', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



--     ('PLASTICO', 0.0, 'KILOGRAMO', 'NEGRO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('PLASTICO', 0.0, 'KILOGRAMO', 'COLOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('TAPA', 0.0, 'UNIDAD', 'ROSCA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('TAPA', 0.0, 'UNIDAD', 'CALCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('ARO_GOMA', 0.0, 'UNIDAD', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('ARO_GOMA', 0.0, 'UNIDAD', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('ARO_GOMA', 0.0, 'UNIDAD', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('TORNILLOS', 0.0, 'UNIDAD', 'TORNILLOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('TORNILLO_GRANDE', 0.0, 'UNIDAD', 'TORNILLO_GRANDE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('TEE', 0.0, 'UNIDAD', 'TEE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('STICKER', 0.0, 'UNIDAD', 'TANQUE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('STICKER', 0.0, 'UNIDAD', 'CAMARA_SEPTICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('RAMAL', 0.0, 'UNIDAD', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('RAMAL', 0.0, 'UNIDAD', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('RAMAL', 0.0, 'UNIDAD', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
