INSERT INTO INSUMO_PRIMARIO (ID, TIPO, CANTIDAD, UNIDAD, SUB_TIPO, CREATED_DATE, LAST_UPDATED_AT)
VALUES
    (1, 'PLASTICO', 0.0, 'KILOGRAMO', 'NEGRO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'PLASTICO', 0.0, 'KILOGRAMO', 'COLOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'TAPA', 0.0, 'UNIDADES', 'ROSCA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'TAPA', 0.0, 'UNIDADES', 'CALCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'ARO_GOMA', 0.0, 'UNIDADES', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 'ARO_GOMA', 0.0, 'UNIDADES', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 'ARO_GOMA', 0.0, 'UNIDADES', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'TORNILLOS', 0.0, 'UNIDADES', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 'TORNILLO_GRANDE', 0.0, 'UNIDADES', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 'TEE', 0.0, 'UNIDADES', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 'STICKER', 0.0, 'UNIDADES', 'TANQUE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12, 'STICKER', 0.0, 'UNIDADES', 'CAMARA_SEPTICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 'RAMAL', 0.0, 'UNIDADES', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 'RAMAL', 0.0, 'UNIDADES', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 'RAMAL', 0.0, 'UNIDADES', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO PRICE_LIST (ID, CREATED_DATE, LAST_UPDATED_AT, NOMBRE, MODIFICADOR)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Minorista', 1.00),
       (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Mayorista', 0.90),
       (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Especial Clientes VIP', 0.85),
       (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista de Distribuidores', 0.80),
       (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Promociones Temporales', 0.75);

INSERT INTO CLIENTE (ID, NOMBRE, TELEFONO, LISTA_PRECIO_ID, CREATED_DATE, LAST_UPDATED_AT)
VALUES
    (1, 'Cliente Juan Pérez', '1122334455', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'Ferretería El Tornillo', '1133445566', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'Distribuidora Norte', '1144556677', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'Obras Sanitarias S.A.', '1155667788', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'VIP Carlos Torres', '1166778899', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO TIPO_TANQUE (
    ID, TIPO, CAPA, CANTIDAD, PLASTICO_NEGRO, PLASTICO_COLOR, COSTO,
    TAPA_TIPO, TORNILLO, TORNILLO_GRANDE, TEE, O_RING, TIPO_STICKER, TAMANO_RAMAL,
    INVENTARIO_PRIMERA, INVENTARIO_SEGUNDA, CREATED_DATE, LAST_UPDATED_AT
) VALUES
      (1, 'TANQUE 500L', 'TRICAPA', 1.0, 8.50, 2.20, 950.00, 'ROSCA', 4, 0, false, 'BIG', 'TANQUE', 'BIG', 15, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      (2, 'TANQUE 1000L', 'TRICAPA', 1.0, 14.00, 3.50, 1300.00, 'ROSCA', 6, 0, false, 'BIG', 'TANQUE', 'BIG', 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      (3, 'TANQUE 1100L', 'BICAPA', 1.0, 12.00, 3.00, 1150.00, 'CALCE', 6, 0, false, 'MEDIUM', 'TANQUE', 'MEDIUM', 8, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      (4, 'CAMARA SÉPTICA 800L', 'UNICAPA', 1.0, 10.00, 0.00, 1050.00, 'CALCE', 0, 4, true, 'SMALL', 'CAMARA_SEPTICA', 'SMALL', 6, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      (5, 'CAMARA SÉPTICA 1200L', 'UNICAPA', 1.0, 13.00, 0.00, 1350.00, 'CALCE', 0, 6, true, 'SMALL', 'CAMARA_SEPTICA', 'BIG', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
