INSERT INTO INSUMO_PRIMARIO (ID, TIPO, CANTIDAD, UNIDAD, SUB_TIPO, CREATED_DATE, LAST_UPDATED_AT)
VALUES
    (1, 'PLASTICO', 0.0, 'KILOGRAMO', 'NEGRO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'PLASTICO', 0.0, 'KILOGRAMO', 'COLOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'TAPA', 0.0, 'UNIDADES', 'ROSCA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, 'TAPA', 0.0, 'UNIDADES', 'CALCE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, 'ARO_GOMA', 0.0, 'UNIDADES', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (6, 'ARO_GOMA', 0.0, 'UNIDADES', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (7, 'ARO_GOMA', 0.0, 'UNIDADES', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (8, 'TORNILLOS', 0.0, 'UNIDADES', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (9, 'TORNILLO_GRANDE', 0.0, 'UNIDADES', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (10, 'TEE', 0.0, 'UNIDADES', 'NONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (11, 'STICKER', 0.0, 'UNIDADES', 'TANQUE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (12, 'STICKER', 0.0, 'UNIDADES', 'CAMARA_SEPTICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (13, 'RAMAL', 0.0, 'UNIDADES', 'BIG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (14, 'RAMAL', 0.0, 'UNIDADES', 'MEDIUM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (15, 'RAMAL', 0.0, 'UNIDADES', 'SMALL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO PRICE_LIST (ID, CREATED_DATE, LAST_UPDATED_AT, NOMBRE, MODIFICADOR)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Minorista', 1.00),
       (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Mayorista', 0.90),
       (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Especial Clientes VIP', 0.85),
       (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista de Distribuidores', 0.80),
       (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Lista Promociones Temporales', 0.75);